language: c

sudo: false

cache:
  directories:
    - ~/.cabal/packages
    - ~/.cabal/store
    - ~/.stack

addons:
  apt:
    packages:
    - libgmp-dev

matrix:
  include:
    - env: TYPE=cabal CABALVER=3.0 GHCVER=8.6.5
      addons: {apt: {packages: [cabal-install-3.0,ghc-8.6.5], sources: [hvr-ghc]}}
    - env: TYPE=cabal CABALVER=3.0 GHCVER=8.6.5 ARGS="-fexcept"
      addons: {apt: {packages: [cabal-install-3.0,ghc-8.6.5], sources: [hvr-ghc]}}
    - env: CABALVER=3.0 GHCVER=8.8.3
      addons: {apt: {packages: [cabal-install-3.0,ghc-8.8.3], sources: [hvr-ghc]}}
    - env: CABALVER=3.0 GHCVER=8.8.3 ARGS="-fexcept"
      addons: {apt: {packages: [cabal-install-3.0,ghc-8.8.3], sources: [hvr-ghc]}}
    - env: TYPE=cabal CABALVER=3.0 GHCVER=8.10.1
      addons: {apt: {packages: [cabal-install-3.0,ghc-8.10.1], sources: [hvr-ghc]}}
    - env: TYPE=cabal CABALVER=3.0 GHCVER=8.10.1 ARGS="-fexcept"
      addons: {apt: {packages: [cabal-install-3.0,ghc-8.10.1], sources: [hvr-ghc]}}
    - env: TYPE=stack ARGS="--stack-yaml stack.yaml"
    - env: TYPE=stack ARGS="--stack-yaml stack.yaml --flag path:except"

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - mkdir -pv ~/.local/bin
  - case "$TYPE" in
      cabal) travis_retry cabal new-update ;;
      stack) travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack' ;;
    esac

script:
  - |
    set -ex # Error out after first failure and print each command before executing
    case "$TYPE" in
      cabal)
        cabal new-build --enable-tests --enable-benchmarks --flags=dev
        cabal new-test --enable-tests --enable-benchmarks --flags=dev
        cabal new-haddock
        cabal new-sdist
        ;;
      stack)
        stack --version
        stack --no-terminal --install-ghc $ARGS test
        ;;
    esac
    set +ex # Stop printing each command

notifications:
  email:
    on_success: never
    on_failure: always
